baseURL = "https://blog.hrt.guide"
languageCode = "zh-CN"
title = "HRT Guide Blog"
theme = "maupassant"
googleAnalytics = ""  # UA-XXXXXXXX-X

## ä¿æŒåˆ†ç±»çš„åŸå§‹åå­—ï¼ˆfalseä¼šåšè½¬å°å†™å¤„ç†ï¼‰
preserveTaxonomyNames = true
## æ˜¯å¦ç¦æ­¢URL Pathè½¬å°å†™
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

# disqusShortname = "yourdiscussshortname"  ## æ˜¯å¦å¼€å¯disqusè¯„è®ºï¼Œä¸è¦å’ŒutterancåŒæ—¶å¼€å¯

[author]
  name = "HRTGuide"

[params]
  author = "HRTGuide"
  subtitle = ""
  keywords = ""
  description = ""
  busuanzi = true #å¯ç”¨ä¸ç®—å­ç½‘é¡µç»Ÿè®¡
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # å¯ç”¨æœ¬åœ°æœç´¢

  # è¿™é‡Œæˆ‘å­˜æ”¾åœ¨äº†ä¸»é¢˜çš„staticæ–‡ä»¶å¤¹é‡Œï¼Œæ ¹ç›®å½•çš„ä¼¼ä¹ä¹Ÿå¯ä»¥
  # customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  # customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # å…¨å±€å¼€å…³ï¼Œä½ ä¹Ÿå¯ä»¥åœ¨æ¯ä¸€ç¯‡å†…å®¹çš„ front matter ä¸­é’ˆå¯¹å•ç¯‡å†…å®¹å…³é—­æˆ–å¼€å¯æŸäº›åŠŸèƒ½
  toc = true  # æ˜¯å¦å¼€å¯ç›®å½•

## å‹æƒ…é“¾æ¥ï¼Œå¯ä»¥å¤šä¸ª

[[params.links]]
  title = "é­”èŒ¶å›½é™…"
  name = "é­”èŒ¶å›½é™…"
  url = "https://magictea.cc/"

## ä¾§è¾¹æ å¹¿å‘Šä½
#[[params.ads]]
#  title = "Ad title"
#  url = "Ad link"
#  img = "Ad img url"

## é…ç½® utterancè¯„è®º,æ•™ç¨‹å‚è€ƒ https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "BBleae/hrt-guide-blog" ##æ¢æˆè‡ªå·±å¾—
  issueTerm = "pathname"
  theme = "github-light"
  label="ğŸ¥ğŸ’¬ğŸ¥"

## å¼€å¯ç‰ˆæƒå£°æ˜ï¼Œåè®®åå­—å’Œé“¾æ¥éƒ½å¯ä»¥æ¢
[params.cc]
    name = "çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç¦æ­¢æ¼”ç» 4.0 å›½é™…è®¸å¯åè®®"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## é…ç½®ä»£ç é«˜äº®
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

## é…ç½®ç½‘ç«™èœå•

[menu]

  [[menu.main]]
    identifier = "archives"
    name = "å½’æ¡£"
    url = "/archives/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "å…³äº"
    url = "/about/"
    weight = 3
